### ISSUE TITLE
Add JDBC re-connect settings

### ISSUE THREAD

**Issue by ChrisMcGowan** [18F/cg-deploy-shibboleth#55]
The current configuration of Tomcat and JDBC assumes that once a DB connection is open it remains opens.  During AWS RDS maintenance windows, connectivity to the DB can be temporary interrupted and Tomcat/JDBC never re-connects and instead errors out.

## Notes

- Review the spring JDBC library and options like `testOnBorrow` to trigger DB reconnects
- Test the release in dev and simulate a temp DB loss and restore to see if Tomcat behaves as expected

## Acceptance Criteria

- [x] That this release handles a DB network connection loss and re-establishes connection

**Comment by jameshochadel** [comment]
uaa-extras integration test suite is failing and requires an update before this can be closed.

**Comment by rcgottlieb** [comment]
It turns out the fix was in shibboleth-boshrelease. There is a property I set the testOnBorrow property incorrectly on a bean. Once I cleaned that up, both deploy-shibboleth and deploy-uaa-extras works in dev. I'm going to let it sit in staging for a bit and then move it into prod.

**Comment by rcgottlieb** [comment]
I am closing this bug, now that I have both uaaextras and Shibboleth running in Production.
